from django.urls import path

from . import views

urlpatterns = [
    path("", views.rotear_dashboard, name="rotear_dashboard"),
    path("entrar/", views.EntrarView.as_view(), name="login"),
    path("sair/", views.SairView.as_view(), name="logout"),
    path("primeiro-acesso/", views.primeiro_acesso, name="primeiro_acesso"),
    path("validar/<uuid:codigo>/", views.validar_comprovante, name="validar_comprovante"),
    path("service-worker.js", views.service_worker, name="service_worker"),

    path("aluno/", views.aluno_dashboard, name="aluno_dashboard"),
    path("tema/<slug:slug>/", views.escolher_modo, name="escolher_modo"),
    path("tema/<slug:slug>/revisar/", views.revisar, name="revisar"),
    path("tema/<slug:slug>/revisar/concluir/", views.concluir_revisao, name="concluir_revisao"),
    path("tema/<slug:slug>/avaliacao/preparacao/", views.pre_avaliacao, name="pre_avaliacao"),
    path("tema/<slug:slug>/avaliacao/iniciar/", views.iniciar_avaliacao, name="iniciar_avaliacao"),
    path("avaliacao/<int:pk>/", views.avaliacao, name="avaliacao"),
    path("avaliacao/<int:pk>/salvar/", views.salvar_resposta, name="salvar_resposta"),
    path("avaliacao/<int:pk>/finalizar/", views.finalizar_avaliacao, name="finalizar_avaliacao"),
    path("avaliacao/<int:pk>/resultado/", views.resultado, name="resultado"),
    path("avaliacao/<int:pk>/feedback/", views.feedback, name="feedback"),
    path("avaliacao/<int:pk>/comprovante.pdf", views.certificado_pdf, name="certificado_pdf"),
    path("tema/<slug:slug>/plantao/", views.plantao, name="plantao"),
    path("chat/<int:sessao_id>/enviar/", views.chat_enviar, name="chat_enviar"),

    path("professor/", views.professor_dashboard, name="professor_dashboard"),
    path("professor/temas/novo/", views.tema_editar, name="tema_novo"),
    path("professor/temas/<int:tema_id>/", views.professor_tema, name="professor_tema"),
    path("professor/temas/<int:tema_id>/editar/", views.tema_editar, name="tema_editar"),
    path("professor/temas/<int:tema_id>/gerar/", views.gerar_pacote, name="gerar_pacote"),
    path("professor/temas/<int:tema_id>/aprovar/", views.aprovar_rascunhos, name="aprovar_rascunhos"),
    path("professor/temas/<int:tema_id>/publicar/", views.publicar_pacote, name="publicar_pacote"),
    path("professor/temas/<int:tema_id>/despublicar/", views.despublicar_pacote, name="despublicar_pacote"),
    path("professor/temas/<int:tema_id>/slides/novo/", views.slide_editar, name="slide_novo"),
    path("professor/temas/<int:tema_id>/slides/<int:slide_id>/", views.slide_editar, name="slide_editar"),
    path("professor/temas/<int:tema_id>/questoes/nova/", views.questao_editar, name="questao_nova"),
    path("professor/temas/<int:tema_id>/questoes/<int:questao_id>/", views.questao_editar, name="questao_editar"),
    path("professor/questoes/<int:questao_id>/status/", views.questao_status, name="questao_status"),
    path("professor/cronograma/novo/", views.aula_editar, name="aula_nova"),
    path("professor/cronograma/<int:aula_id>/", views.aula_editar, name="aula_editar"),
    path("professor/alunos/<int:aluno_id>/", views.aluno_editar, name="aluno_editar"),
    path("professor/tentativas/<int:tentativa_id>/", views.tentativa_detalhe, name="tentativa_detalhe"),
    path("professor/tentativas/<int:tentativa_id>/nota/", views.ajustar_nota, name="ajustar_nota"),
    path("professor/tentativas/<int:tentativa_id>/feedback/", views.reprocessar_feedback, name="reprocessar_feedback"),
    path("professor/fontes/", views.professor_fontes, name="professor_fontes"),
    path("professor/fontes/nova/", views.fonte_editar, name="fonte_nova"),
    path("professor/fontes/<int:fonte_id>/", views.fonte_editar, name="fonte_editar"),
    path("professor/fontes/<int:fonte_id>/importar/", views.fonte_importar, name="fonte_importar"),
    path("professor/relatorios/", views.relatorios, name="relatorios"),
    path("professor/relatorios/csv/", views.relatorio_csv, name="relatorio_csv"),
    path("professor/relatorios/pdf/", views.relatorio_pdf, name="relatorio_pdf"),
]
